version: "3.9"

services:
    php:
        container_name: classic-blog
        image: php
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:80" 
        volumes:
            - ./src:/var/www/html
